# Generated by Django 4.1.7 on 2023-02-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='requisicao',
            field=models.CharField(max_length=100),
        ),
    ]
