# Generated by Django 4.1.7 on 2023-02-17 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisicao', '0002_ticket_alter_requisicao_requisicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Para resolver'), ('R', 'Resolvido')], default='P', max_length=1)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='requisicao.requisicao')),
                ('tickets', models.ManyToManyField(to='requisicao.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
